### ISSUE TITLE
npm error on mac

### ISSUE THREAD

**Issue by filippomc** [openworm/geppetto-application#46]
This error does not seems to affect nwb-explorer but I found a possible explanation related to running the install script on macos with conda:

This seems to be the problem: Zilliqa/kaya#74

fsevents@1.0.17 install /Users/snakes/Desktop/nwb-explorer/webapp/node_modules/react-scripts/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [ '/usr/local/bin/node',
node-pre-gyp verb cli   '/Users/snakes/Desktop/nwb-explorer/webapp/node_modules/react-scripts/node_modules/fsevents/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build' ]
node-pre-gyp info using node-pre-gyp@0.6.32
node-pre-gyp info using node@10.15.3 | darwin | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/Users/snakes/Desktop/nwb-explorer/webapp/node_modules/react-scripts/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.17/fse-v1.0.17-node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.17/fse-v1.0.17-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.17/fse-v1.0.17-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.17 and node@10.15.3 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.17/fse-v1.0.17-node-v64-darwin-x64.tar.gz 
node-pre-gyp verb command build [ 'rebuild' ]
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.17/fse-v1.0.17-node-v64-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.17 and node@10.15.3 (node-v64 ABI) (falling back to source compile with node-gyp) 
node-pre-gyp http Connection closed while downloading tarball file 
node-pre-gyp verb command build [ 'rebuild' ]
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /Users/snakes/miniconda3/envs/nwb/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
gyp ERR! stack     at Socket.emit (events.js:189:13)
gyp ERR! stack     at Pipe._handle.close (net.js:597:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/snakes/Desktop/nwb-explorer/webapp/node_modules/react-scripts/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/snakes/Desktop/nwb-explorer/webapp/node_modules/react-scripts/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/snakes/Desktop/nwb-explorer/webapp/node_modules/react-scripts/node_modules/fsevents
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
gyp ERR! configure error 
node-pre-gyp ERR! build error 
gyp ERR! stack Error: Command failed: /Users/snakes/miniconda3/envs/nwb/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! node-pre-gypstack   File "<string>", line 1
 ERR!gyp  ERR!stack  Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/snakes/Desktop/nwb-explorer/webapp/node_modules/react-scripts/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/snakes/Desktop/nwb-explorer/webapp/node_modules/react-scripts/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)
stacknode-pre-gyp     import sys; print "%s.%s.%s" % sys.version_info[:3];
 gypERR!  ERR!stack      at ChildProcess.<anonymous> (/Users/snakes/Desktop/nwb-explorer/webapp/node_modules/react-scripts/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
stacknode-pre-gyp                                ^
 gyp ERR! ERR!stack      at ChildProcess.emit (events.js:189:13)
stack SyntaxError: invalid syntax
node-pre-gyp gyp ERR!ERR!  stack     at maybeClose (internal/child_process.js:970:16)
stack 
node-pre-gypgyp  ERR!ERR!  stackstack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gypgyp  ERR!ERR!  stackSystem     at Socket.stream.socket.on (internal/child_process.js:389:11)
 Darwin 18.5.0
gyp ERR! node-pre-gypstack      at Socket.emit (events.js:189:13)
ERR!gyp  commandERR! "/usr/local/bin/node" "/Users/snakes/Desktop/nwb-explorer/webapp/node_modules/react-scripts/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
 stacknode-pre-gyp     at Pipe._handle.close (net.js:597:12)
 ERR! cwd /Users/snakes/Desktop/nwb-explorer/webapp/node_modules/react-scripts/node_modules/fsevents
node-pre-gyp ERR! node -v v10.15.3
gyp node-pre-gypERR!  ERR!System  Darwin 18.5.0
node-pre-gyp -v v0.6.32
node-pre-gypgyp  ERR!ERR!  not okcommand 
 "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/snakes/Desktop/nwb-explorer/webapp/node_modules/react-scripts/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/snakes/Desktop/nwb-explorer/webapp/node_modules/react-scripts/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp ERR! cwd /Users/snakes/Desktop/nwb-explorer/webapp/node_modules/react-scripts/node_modules/fsevents
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/snakes/Desktop/nwb-explorer/webapp/node_modules/react-scripts/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node --module_name=fse --module_path=/Users/snakes/Desktop/nwb-explorer/webapp/node_modules/react-scripts/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64' (1)

**Comment by filippomc** [comment]
moved from https://github.com/MetaCell/nwb-explorer/issues/47
